apiVersion: apps/v1
kind: Deployment
metadata:
  name: sudo01
spec:
  selector:
    matchLabels:
      app: sudo01-pod
  template:
    metadata:
      labels:
        app: sudo01-pod
    spec:
      containers:
      - name: sudo01-container
        image: barclaysacr02.azurecr.io/sudo01:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
